version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: Zookeeper
    expose:
      - 2181
  kafka:
    image: wurstmeister/kafka
    container_name: Kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.19
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-gui:
    image: provectuslabs/kafka-ui:latest
    container_name: Kafka-GUI
    ports: 
      - 8081:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: "zookeeper:2181"
